CONFIG_ZMK_POINTING=y
CONFIG_ZMK_ANIMATION=y
CONFIG_SPI=y
CONFIG_ZMK_DRIVER_EXT_POWER_TRANSIENT=y
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_INTERVAL_MS=250
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=50
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=y
CONFIG_RGBLED_WIDGET_LAYER_COLOR=7
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=4096
CONFIG_GPIO_HOGS=y
CONFIG_I2C=y
CONFIG_PAT9125=y
CONFIG_EQUINOX_PAT_DIAGNOSTICS=y
CONFIG_LOG_PRINTK=n
CONFIG_INPUT_LOG_LEVEL_DBG=y
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
